/**
 * Jspreadsheet Configuration
 * 
 * Daily license key from: https://jspreadsheet.com/docs/getting-started
 * Note: This is a daily trial key that expires after 24 hours.
 * Get a fresh key from the documentation if needed.
 */

export const JSPREADSHEET_LICENSE_KEY = "ZDEwYTJmOGIxYjkxN2M4ZjFlODlkODU4ODI4ODAyNjIzYzQ5YjFjNjNiOTkwNTE2Y2E4Y2FlMWEwNmRhNjk5MjY0MjI4Y2JmMDAxNTkxNzlmOWYzOWFlZTE1ZjJkNGMxMTcxZmYyZmU3MzdiMGQ4NWQzYjUzZmZkYmRlZTJlNjMsZXlKamJHbGxiblJKWkNJNklpSXNJbTVoYldVaU9pSktjM0J5WldGa2MyaGxaWFFpTENKa1lYUmxJam94TnpZMU1EQXpOek16TENKa2IyMWhhVzRpT2xzaWFuTndjbVZoWkhOb1pXVjBMbU52YlNJc0ltTnZaR1Z6WVc1a1ltOTRMbWx2SWl3aWFuTm9aV3hzTG01bGRDSXNJbU56WWk1aGNIQWlMQ0p6ZEdGamEySnNhWFI2TG1sdklpd2lkMlZpWTI5dWRHRnBibVZ5TG1sdklpd2liRzlqWVd4b2IzTjBJbDBzSW5Cc1lXNGlPaUl6TkNJc0luTmpiM0JsSWpwYkluWTNJaXdpZGpnaUxDSjJPU0lzSW5ZeE1DSXNJbll4TVNJc0luWXhNaUlzSW1Ob1lYSjBjeUlzSW1admNtMXpJaXdpWm05eWJYVnNZU0lzSW5CaGNuTmxjaUlzSW5KbGJtUmxjaUlzSW1OdmJXMWxiblJ6SWl3aWFXMXdiM0owWlhJaUxDSmlZWElpTENKMllXeHBaR0YwYVc5dWN5SXNJbk5sWVhKamFDSXNJbkJ5YVc1MElpd2ljMmhsWlhSeklpd2lZMnhwWlc1MElpd2ljMlZ5ZG1WeUlpd2ljMmhoY0dWeklpd2labTl5YldGMElsMHNJbVJsYlc4aU9uUnlkV1Y5"
